export const MAIN_ROUTE = '/'
export const CATALOG_ROUTE = '/catalog'
export const CONTACTS_ROUTE = '/contacts'
export const TRADEIN_ROUTE = '/trade-in'
export const COMMISSION_ROUTE = '/commission'
export const DETAILING_ROUTE = '/detailing'