export const MAIN_ROUTE = '/'
export const CATALOG_ROUTE = '/catalog'
export const CONTACTS_ROUTE = '/contacts'
export const TRADEIN_ROUTE = '/trade-in'
export const COMMISSION_ROUTE = '/commission'
export const DETAILING_ROUTE = '/detailing'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const PROFILE_ROUTE = '/profile'
export const ADD_CAR_ROUTE = '/add-car'
export const CAR_PAGE_ROUTE = '/car'
export const FAVORITE_CAR_ROUTE = '/favorites'
export const HISTORY_CAR_ROUTE = '/history'
export const APPLICATIONS_ROUTE = '/applications'
export const REFERENCE_ROUTER = '/about'

